kieraneglin/pinchflat

- lib/pinchflat/profiles/media_profile.ex
- lib/pinchflat/profiles/options/yt_dlp/download_option_builder.ex
- lib/pinchflat_web/components/core_components.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
- test/pinchflat/profiles/options/yt_dlp/download_option_builder_test.exs
- Adds support for only downloading audio for the provided source
- Improves media profile form explainers
N/A
N/A
> Support audio only downloads

- lib/pinchflat_web/controllers/sources/source_html.ex
- lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
N/A
- Improves language around index frequency when setting a frequency <= 0
N/A
N/A
> Clarify wording of source form for index frequency

- README.md
- test/pinchflat/utils/filesystem_utils/file_follower_server_test.exs
N/A
- Made some more small changes to the README. Still a ways to go!
- Hopefully fixed a flaky test
N/A
> More README

- config/runtime.exs
N/A
N/A
- Fixed log level runtime config to correctly compare an atom against an atom instead of an atom against a string
N/A
> [Bugfix] Runtime log level fix

- lib/pinchflat/sources/source.ex
- lib/pinchflat/startup_tasks.ex
- lib/pinchflat_web.ex
- lib/pinchflat_web/components/core_components.ex
- lib/pinchflat_web/components/custom_components/button_components.ex
- lib/pinchflat_web/components/layouts.ex
- lib/pinchflat_web/components/layouts/partials/donate_modal.heex
- lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
- lib/pinchflat_web/components/layouts/partials/upgrade_button_live.ex
- lib/pinchflat_web/components/layouts/partials/upgrade_modal.heex
- lib/pinchflat_web/components/layouts/root.html.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/index.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/new.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
- lib/pinchflat_web/controllers/pages/page_html/onboarding_checklist.html.heex
- lib/pinchflat_web/controllers/searches/search_html/show.html.heex
- lib/pinchflat_web/controllers/sources/source_html/edit.html.heex
- lib/pinchflat_web/controllers/sources/source_html/index.html.heex
- lib/pinchflat_web/controllers/sources/source_html/new.html.heex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
- lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
- Adds "pro" upgrade modal for fast indexing
- Don't stress - it's free! Just trying something new for supporting an OSS project
- Adds donation and github links to sidebar
- Updates custom link components to use `href` instead of `navigate`
- Adds optional `label_suffix` to custom input elements
N/A
N/A
> Add support modals

- dev.Dockerfile
- Add local details to local dockerfile
N/A
N/A
N/A
> Add local details to local dockerfile

- lib/pinchflat_web/components/custom_components/text_components.ex
- lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/index.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
- lib/pinchflat_web/controllers/pages/page_html/onboarding_checklist.html.heex
- lib/pinchflat_web/controllers/searches/search_html/show.html.heex
- lib/pinchflat_web/controllers/sources/source_html/edit.html.heex
- lib/pinchflat_web/controllers/sources/source_html/index.html.heex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
- test/pinchflat_web/controllers/media_profile_controller_test.exs
- test/pinchflat_web/controllers/source_controller_test.exs
N/A
- Improves index tables to make it easier to see details about a source or media profile by clicking its title (resolves #92)
- Improves consistency of displaying source/media profile names (resolves #91)
N/A
N/A
> Improve index tables and improved consistency

- .iex.exs
- .sobelow-conf
- README.md
- lib/pinchflat/boot/pre_job_startup_tasks.ex
- lib/pinchflat/media/media_item.ex
- lib/pinchflat/sources/source.ex
- lib/pinchflat_web/controllers/media_items/media_item_controller.ex
- lib/pinchflat_web/controllers/media_items/media_item_html.ex
- lib/pinchflat_web/controllers/media_items/media_item_html/media_preview.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
- lib/pinchflat_web/router.ex
- priv/repo/migrations/20240323165649_add_uuid_to_source_and_media.exs
- test/pinchflat/media_test.exs
- test/pinchflat/sources_test.exs
- test/pinchflat_web/controllers/media_item_controller_test.exs
- test/support/fixtures/media_fixtures.ex
- Adds endpoint for streaming media, supporting range requests
- Adds UUID fields to media items and sources
N/A
N/A
N/A
> Add media streaming

- README.md
- lib/pinchflat/boot/pre_job_startup_tasks.ex
- lib/pinchflat/filesystem/filesystem_helpers.ex
- lib/pinchflat/release.ex
- rel/overlays/bin/check_file_permissions
- rel/overlays/bin/docker_start
- test/pinchflat/filesystem/filesystem_helpers_test.exs
N/A
- Adds README entry on Portainer (see: #105)
- Improves permissions error to be more helpful (see: #106)
N/A
> Improve preflight file permissions check

- README.md
N/A
- GHCR support was added directly to `master` but this updates the README. (Resolves #109)
N/A
N/A
> Add GHCR support

- .iex.exs
- README.md
- config/config.exs
- config/dev.exs
- config/runtime.exs
- lib/pinchflat/boot/pre_job_startup_tasks.ex
- lib/pinchflat/downloading/download_option_builder.ex
- lib/pinchflat/release.ex
- lib/pinchflat/yt_dlp/command_runner.ex
- selfhosted.Dockerfile
- test/pinchflat/downloading/download_option_builder_test.exs
- test/pinchflat/yt_dlp/command_runner_test.exs
- test/test_helper.exs
- Adds ability to provide YouTube cookies to allow downloading private playlists ([docs](https://github.com/kieraneglin/pinchflat/wiki/YouTube-Cookies))
N/A
N/A
N/A
> Cookie auth

- config/runtime.exs
- lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
- selfhosted.Dockerfile
- Exposes port in Dockerfile (hopefully resolves #126)
- Adds current app version to sidebar
- Switched from forcing IPv6 to IPv4 (resolves #128)
N/A
N/A
> [Bugfix] Expose port in Dockerfile and force IPv4

- lib/pinchflat/media/media.ex
- test/pinchflat/media_test.exs
N/A
N/A
- updates fast indexing to respect title filter regex
N/A
> [Bugfix] updated fast indexing to respect title filter regex

- lib/pinchflat/fast_indexing/fast_indexing_helpers.ex
- lib/pinchflat/media/media.ex
- lib/pinchflat/media/media_query.ex
- lib/pinchflat/sources/sources.ex
- lib/pinchflat_web/controllers/sources/source_controller.ex
- test/pinchflat/media_test.exs
N/A
- Extracted out query logic from `Media` context into individual query parts I can compose into a larger query
- Just trying something out! If I like it I'll refactor more modules and if not I'll rip this out
N/A
N/A
> [Refactor] Refactored Media context into context + queries

- .github/workflows/release.yml
This will create a docker image when a new release is published with the tag being the release tag.
> [Housekeeping] Add release workflow

- .github/workflows/docker_release.yml
- .github/workflows/release.yml
- Originally authored by @onedr0p in #141 - taking over to run linting and try combining with existing Docker action
N/A
N/A
N/A
> [Housekeeping] Add release workflow (takeover)

- lib/pinchflat/boot/pre_job_startup_tasks.ex
- lib/pinchflat/yt_dlp/backend_command_runner.ex
- lib/pinchflat/yt_dlp/command_runner.ex
- lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
- test/pinchflat/yt_dlp/command_runner_test.exs
- test/support/scripts/yt-dlp-mocks/repeater.sh
- Adds yt-dlp version to sidebar
N/A
N/A
N/A
> [Housekeeping] Add yt-dlp version to sidebar

- assets/js/app.js
- assets/js/tabs.js
- lib/pinchflat_web/components/custom_components/tab_components.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
N/A
- Tab state is now maintained when you navigate/reload (works toward #158)
N/A
N/A
> [Enhancement] Retain tab state using location hash

- config/config.exs
- lib/pinchflat_web/components/custom_components/tab_components.ex
- lib/pinchflat_web/endpoint.ex
- Enables asset compression in prod
- Upgrades Tailwind from 3.3.2 to 3.4.3
N/A
N/A
> [Housekeeping] Upgraded Tailwind to 3.4.3

- lib/pinchflat/media/media.ex
- lib/pinchflat/media/media_query.ex
- lib/pinchflat/podcasts/podcast_helpers.ex
- lib/pinchflat/sources/sources_query.ex
- lib/pinchflat_web/components/custom_components/tab_components.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_controller.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
- lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
- lib/pinchflat_web/controllers/sources/source_controller.ex
- test/pinchflat/media_test.exs
N/A
- Updated models to list either alphabetically or ID descending, depending on what makes sense in-context. This applies to the index pages, association tabs, and select fields in forms
- Refactored media queries to be completely self-contained if the previous argument was referencing some an association on that record
N/A
N/A
> [Enhancement] Improve ordering of models

- lib/pinchflat/utils/number_utils.ex
- lib/pinchflat_web/components/custom_components/table_components.ex
- lib/pinchflat_web/controllers/sources/source_controller.ex
- lib/pinchflat_web/controllers/sources/source_html/media_item_table_live.ex
- lib/pinchflat_web/controllers/sources/source_html/pending_table_live.ex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
- test/pinchflat/utils/number_utils_test.exs
- test/pinchflat_web/controllers/sources/media_item_table_live_test.exs
- Adds basic pagination to a source's media so all pending/downloaded records are accessible now! (works toward #158)
N/A
N/A
N/A
> [Enhancement] Add pagination for a source's media

- lib/pinchflat_web/components/core_components.ex
- lib/pinchflat_web/components/custom_components/text_components.ex
- lib/pinchflat_web/controllers/media_items/media_item_html/media_preview.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
- lib/pinchflat_web/controllers/pages/page_html/home.html.heex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
N/A
- Tweaks the media item page to better use space on large displays
N/A
N/A
> [Enhancement] Improve layout of media item page on large displays

- lib/pinchflat/downloading/media_download_worker.ex
- test/pinchflat/downloading/media_download_worker_test.exs
N/A
- Download jobs for unavailable videos will now be discarded instead of immediately retried since that won't fix the issue. They will still be retried _at next index_ just in case but this change stops them from being retried as part of job failure logic (related to #205)
N/A
N/A
> [Housekeeping] Prevent unavailable videos from being immediately retried

- assets/js/alpine_helpers.js
- assets/js/app.js
- lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
- Adds link to release notes page in sidebar
- Adds  `"NEW"` pill on sidebar when a new release is published
- This pill is dismissed on the next pageload after you click it
N/A
N/A
N/A
> [Enhancement] Add in-app indicator when a new release is published

- lib/pinchflat_web/controllers/sources/source_html/media_item_table_live.ex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
- Adds reload button to "live" tables (essentially, source's pending/downloaded media)
N/A
N/A
N/A
> [Enhancement] Add reload button to "live" tables

- assets/js/alpine_helpers.js
- lib/pinchflat_web/controllers/media_items/media_item_html/actions_dropdown.html.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/edit.html.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/actions_dropdown.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/new.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
- lib/pinchflat_web/controllers/searches/search_html/show.html.heex
- lib/pinchflat_web/controllers/settings/setting_html/setting_form.html.heex
- lib/pinchflat_web/controllers/settings/setting_html/show.html.heex
- lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
- lib/pinchflat_web/controllers/sources/source_html/edit.html.heex
- lib/pinchflat_web/controllers/sources/source_html/new.html.heex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
- Add "Copy JSON" action button to help when troubleshooting
N/A
- FIxed CSS issue that caused the action dropdown to sit behind its parent container
N/A
> [Enhancement] Add "Copy JSON" action button to help when troubleshooting

- lib/pinchflat_web/components/core_components.ex
- lib/pinchflat_web/components/custom_components/button_components.ex
- lib/pinchflat_web/controllers/settings/setting_html.ex
- lib/pinchflat_web/controllers/settings/setting_html/apprise_server_live.ex
- lib/pinchflat_web/controllers/settings/setting_html/setting_form.html.heex
- lib/pinchflat_web/controllers/settings/setting_html/show.html.heex
- lib/pinchflat_web/controllers/sources/source_html/media_item_table_live.ex
- test/pinchflat_web/controllers/settings/apprise_server_live_test.exs
- Adds a button that sends a test notification to your Apprise server (resolves #217)
N/A
N/A
N/A
> [Enhancement] Add test button to Apprise server input

- README.md
- lib/pinchflat_web/components/layouts/partials/donate_modal.heex
- lib/pinchflat_web/components/layouts/partials/upgrade_button_live.ex
- lib/pinchflat_web/components/layouts/partials/upgrade_modal.heex
N/A
- Updated "pro" and donation modal to direct people straight to the EFF instead of donating to me
N/A
N/A
> [Misc.] Direct donations directly to the EFF

- lib/pinchflat/yt_dlp/command_runner.ex
- test/pinchflat/yt_dlp/command_runner_test.exs
- Adds a cache dir for `yt-dlp`
N/A
N/A
N/A
> [Enhancement] Support yt-dlp caching

- lib/pinchflat_web/controllers/settings/setting_html/app_info.html.heex
N/A
N/A
Fixed a typo on the "Copy Diagnostic Info" button.
N/A
> [Typo] Fix spelling on app info page

- lib/pinchflat/application.ex
- lib/pinchflat/downloading/media_download_worker.ex
- lib/pinchflat/downloading/media_quality_upgrade_worker.ex
- lib/pinchflat/fast_indexing/fast_indexing_worker.ex
- lib/pinchflat/metadata/source_metadata_storage_worker.ex
- lib/pinchflat/slow_indexing/media_collection_indexing_worker.ex
- lib/pinchflat/tasks/tasks_query.ex
- lib/pinchflat_web/controllers/pages/page_controller.ex
- lib/pinchflat_web/controllers/pages/page_html/history_table_live.ex
- lib/pinchflat_web/controllers/pages/page_html/home.html.heex
- lib/pinchflat_web/controllers/pages/page_html/job_table_live.ex
- lib/pinchflat_web/telemetry.ex
- test/pinchflat_web/controllers/pages/job_table_live_test.exs
- Shows currently executing jobs on homepage to give an indication of progress happening
- Uses websockets + events from an Erlang telemetry hook to give real-time updates
N/A
N/A
N/A
> [Enhancement] Show currently executing jobs on homepage

- lib/pinchflat/downloading/download_option_builder.ex
- lib/pinchflat/profiles/media_profile.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
- test/pinchflat/downloading/download_option_builder_test.exs
- Does what it says on the tin! (related to #252)
N/A
N/A
N/A
> [Enhancement] Add support for 8k downloads

- lib/pinchflat/downloading/media_retention_worker.ex
- lib/pinchflat/media/media_query.ex
- test/pinchflat/downloading/media_retention_worker_test.exs
- test/pinchflat/media_test.exs
N/A
N/A
- Fixes bug where the retention date logic would hold on to items for one day longer than it should
- Resolves #428
N/A
> [Bugfix] Fix off-by-1 error for retention date logic

- lib/pinchflat_web/components/custom_components/text_components.ex
- lib/pinchflat_web/controllers/media_items/media_item_html/actions_dropdown.html.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/media_preview.heex
- lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html/actions_dropdown.html.heex
- lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
- lib/pinchflat_web/controllers/sources/source_html/show.html.heex
N/A
- Made the video preview take up a full column on XL devices (resolves #430)
- Update tasks table to have their execution times localized based on the user's timezone (resolves #429)
- Make the links in the rendered video description clickable
- Fixed the way the `Copy JSON` action handles newline characters
N/A
N/A
> [Enhancement] Misc. UI updates

- lib/pinchflat/profiles/media_profile.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
- test/pinchflat/downloading/quality_option_builder_test.exs
- Add support for 1440p as a preferred resolution
- Resolves #497 
N/A
N/A
N/A
> [Enhancement] Add support for 1440p as a preferred resolution

- lib/pinchflat/downloading/download_option_builder.ex
- lib/pinchflat/profiles/media_profile.ex
- lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
- test/pinchflat/downloading/download_option_builder_test.exs
- Adds the ability for SponsorBlock to insert chapter markers rather than deleting the section entirely
- Resolves #541
N/A
N/A
N/A
> [Enhancement] Mark chapters with SponsorBlock

- README.md
- lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
- Adds Discord link to README and sidebar
N/A
N/A
N/A
> [Enhancement] Add Discord link

- README.md
- docker/selfhosted.Dockerfile
- rel/overlays/bin/docker_start
- Adds a new UMASK env var that's set to `022` by default
- Resolves #558 
N/A
N/A
N/A
> [Enhancement] Add support for UMASK environment variable

- lib/pinchflat_web/endpoint.ex
- lib/pinchflat_web/router.ex
- Stops logging Docker healthcheck requests
- Resolves #638
N/A
N/A
N/A
> [Enhancement] Stop logging Docker healthcheck requests

- lib/pinchflat/slow_indexing/file_follower_server.ex
N/A
- The old file follower server messaging could be seen as a bad thing based on its wording. Updated wording to indicate that seeing its messages is, in fact, a good thing
N/A
N/A
> [Dev] Improve internal file follower server messaging

- lib/pinchflat_web/controllers/sources/source_live/index_table_live.ex
- test/pinchflat_web/controllers/sources/index_table_live_test.exs
N/A
- Sorting sources is now case-insensitive
- Resolves #690
N/A
N/A
> [Enhancement] Sorting sources is now case-insensitive
