config/config.exs
lib/pinchflat/media/media_item.ex
lib/pinchflat/tasks/media_item_tasks.ex
lib/pinchflat/tasks/source_tasks.ex
lib/pinchflat/workers/filesystem_data_worker.ex
lib/pinchflat/workers/video_download_worker.ex
priv/repo/migrations/20240303021902_add_media_size_to_media_item.exs
test/pinchflat/tasks/media_items_tasks_test.exs
test/pinchflat/workers/filesystem_data_worker_test.exs
test/pinchflat/workers/video_download_worker_test.exs

- Adds `media_size_bytes` attribute to track media filesize
- Adds workers, methods, etc. for fetching and storing media filesize
N/A
N/A
N/A

Track media filesize in DB

---

.iex.exs
config/dev.exs
config/test.exs
lib/pinchflat/media_client/backends/yt_dlp/media.ex
lib/pinchflat/media_client/backends/yt_dlp/media_collection.ex
lib/pinchflat/media_client/backends/yt_dlp/metadata_file_helpers.ex
lib/pinchflat/media_client/media_downloader.ex
lib/pinchflat/media_client/source_details.ex
lib/pinchflat/profiles/media_profile.ex
lib/pinchflat/tasks/source_tasks.ex
lib/pinchflat/workers/media_download_worker.ex
test/pinchflat/media_client/backends/yt_dlp/command_runner_test.exs
test/pinchflat/media_client/backends/yt_dlp/media_collection_test.exs
test/pinchflat/media_client/backends/yt_dlp/media_test.exs
test/pinchflat/media_client/backends/yt_dlp/metadata_parser_test.exs
test/pinchflat/media_client/media_downloader_test.exs
test/pinchflat/profiles/options/yt_dlp/download_option_builder_test.exs
test/pinchflat/sources_test.exs
test/pinchflat/tasks/source_tasks_test.exs
test/pinchflat/workers/media_download_worker_test.exs
test/pinchflat/workers/media_indexing_worker_test.exs

- Adds a test I forgot to include in #49 
- Renamed video-related modules, files, and some methods/comments to reflect the fact that they may not be downloading a video
- This is pretty minor change ultimately, but I think it's best to make it clear that we aren't _always_ interacting with a video. It could be audio or (maybe in the future) just metadata.
- Intentionally doesn't update _all_ comments or UI since it can be more clear to talk about videos depending on the context
N/A
N/A

Rename video-related modules to be media-related

---

README.md
config/config.exs
config/runtime.exs
lib/pinchflat_web/router.ex
test/pinchflat_web/routing_test.exs

N/A
- Changed the name of the basic auth vars to better reflect their purpose
- Basic auth credentials were set to be consumed at compiletime, but we actually need them set at runtime. Updated `runtime.exs` to accomplish this
- Basic auth credentials were being respected even if they were empty strings. Empty strings are now ignored.
N/A

[Bugfix] Fix basic auth in deployed apps

---

.github/workflows/build_and_push_docker.yml

N/A
- Updates docker build runner to optionally accept the tag you want to attach to the build
N/A
N/A

Add image tag input to Github actions

---

.iex.exs
lib/pinchflat/application.ex
lib/pinchflat/profiles/media_profile.ex
lib/pinchflat/settings.ex
lib/pinchflat/settings/setting.ex
lib/pinchflat/startup_tasks.ex
lib/pinchflat_web.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_controller.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/new.html.heex
lib/pinchflat_web/controllers/pages/page_controller.ex
lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html/new.html.heex
priv/repo/migrations/20240306173305_create_settings.exs
test/pinchflat/settings_test.exs
test/pinchflat/startup_tasks_test.exs
test/pinchflat_web/controllers/media_profile_controller_test.exs
test/pinchflat_web/controllers/page_controller_test.exs
test/pinchflat_web/controllers/source_controller_test.exs

- Adds settings model for getting/setting user-level configuration in the DB
- Adds a module for running tasks on app boot (currently: ensuring default settings exist)
- Updates onboarding flow to use new settings model instead of session data
N/A
N/A

Add settings model

---

config/runtime.exs

- Adds log level to runtime config, enforcing it's either `debug` or `info`
N/A
N/A
N/A

Adds log level to runtime config

---

lib/pinchflat/media.ex
test/pinchflat/media_test.exs

N/A
N/A
- Fixed a bug where searching would throw an error if one of the searchable columns (ie: title, description) is null, regardless of whether that column contained a search term
- The issue is that passing `null` to SQLite's `snippet` would make it return `null` and breaking the whole concatenation routine. So `matching_search_term` would get set to `nil`, later breaking the UI highlight function because it tries to call `String.split/3` on `nil`
- The fix is to coalesce the `snippet` calls so they always return a string
N/A

[Bugfix] Resolves bug with null values in search

---

lib/pinchflat/media.ex
lib/pinchflat/media/media_item.ex
lib/pinchflat/tasks/source_tasks.ex
lib/pinchflat/yt_dlp/backend/media.ex
lib/pinchflat/yt_dlp/backend/media_collection.ex
priv/repo/migrations/20240309052602_add_short_form_to_media_items.exs
test/pinchflat/media_test.exs
test/pinchflat/tasks/media_items_tasks_test.exs
test/pinchflat/tasks/source_tasks_test.exs
test/pinchflat/yt_dlp/backend/media_collection_test.exs
test/pinchflat/yt_dlp/backend/media_test.exs
test/support/fixtures/media_fixtures.ex
test/support/fixtures/sources_fixtures.ex

- Adds a `short_form_content` field to `MediaItem`
- Adds a new `Media` (from yt-dlp modules) struct and method to transform a response into a struct
- This method uses the URL, aspect ratio, and duration to try and determine if content is a short
- Updates yt-dlp media attribute methods to ask for `webpage_url` instead of `original_url`
- Updates yt-dlp media attribute methods to ask for `aspect_ratio` and `duration`
N/A
N/A

Improve short detection

---

config/config.exs
lib/pinchflat/api/youtube_rss.ex
lib/pinchflat/sources.ex
lib/pinchflat/sources/source.ex
lib/pinchflat/tasks/source_tasks.ex
lib/pinchflat/workers/fast_indexing_worker.ex
lib/pinchflat/workers/media_collection_indexing_worker.ex
lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html/fast_indexing_help.html.heex
lib/pinchflat_web/controllers/sources/source_html/show.html.heex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
priv/repo/migrations/20240309182418_add_fast_index_to_sources.exs
test/pinchflat/sources_test.exs
test/pinchflat/tasks/source_tasks_test.exs
test/pinchflat/workers/fast_indexing_worker_test.exs
test/pinchflat/workers/media_collection_indexing_worker_test.exs

- Adds `fast_index` field to sources and hooked up all lifecycle updates around it
- Adds fast indexing worker and hooked it up to other indexing workers
- Updated sources UI to now only show pending tasks instead of all tasks
N/A
N/A

Fast index UI

---

lib/pinchflat/application.ex
lib/pinchflat/startup_tasks.ex
lib/pinchflat/workers/data_backfill_worker.ex
lib/pinchflat/workers/fast_indexing_worker.ex
test/pinchflat/workers/data_backfill_worker_test.exs

- Adds new worker for backfilling local data. Useful for ensuring existing data conforms to future schema changes
- As the first change, this worker updates `short_form_content` for media items based on the `original_url`. This is to let existing shorts work with the new short detection logic in #59 
- Updates existing startup task to kick off this new worker
N/A
N/A

Local data worker improvements

---

config/config.exs
config/dev.exs

N/A
N/A
- Disables `check_origin` for websockets in release environment.
- NOTE: this must be changed if you ever deploy to a traditional deployment environment (read: not selfhosted)
N/A

[Bugfix] Update check origin in release environment

---

.iex.exs
lib/pinchflat/media.ex
lib/pinchflat/media/media_item.ex
lib/pinchflat/sources.ex
lib/pinchflat/sources/source.ex
lib/pinchflat/tasks/source_tasks.ex
lib/pinchflat/yt_dlp/backend/media.ex
lib/pinchflat_web/components/core_components.ex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
priv/repo/migrations/20240310230713_add_uploaded_at_to_media_items.exs
priv/repo/migrations/20240311033214_add_download_cutoff_date_to_sources.exs
test/pinchflat/media_test.exs
test/pinchflat/sources_test.exs
test/pinchflat/tasks/media_items_tasks_test.exs
test/pinchflat/tasks/source_tasks_test.exs
test/pinchflat/yt_dlp/backend/media_test.exs
test/support/fixtures/media_fixtures.ex
test/support/fixtures/sources_fixtures.ex
test/support/testing_helper_methods.ex

- Adds ability to specify a download cutoff date where only media from after that date will be downloaded. Related to #60 
- Adds `upload_date` to media items
- Updates media item creation during indexing to have `ON CONFLICT UPDATE` logic rather than failing the insert
N/A
N/A

Download cutoff date for sources

---

.check.exs
dev.Dockerfile
ideas.md
selfhosted.Dockerfile

N/A
- Upgrade to Elixir 1.16.2
- Updated selfhosted Dockerfile:
- Installs `yt-dlp` using a binary instead
- Removes password from root user. See comments for rationale
- The upgrade allowed me to remove some workarounds from the `mix check` command
N/A

Upgrade to Elixir 1.16.2

---

lib/pinchflat/yt_dlp/download_option_builder.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
test/pinchflat/yt_dlp/download_option_builder_test.exs

N/A
- Updates audio fetching logic to return the highest-quality M4A possible (related to #61)
- This inadvertently allows embedding thumbnails and metadata so that's been updated accordingly
N/A
I ran a lot of tests around sorting by best M4A (read: AAC) and extracting that vs. getting the best _period_ (usually OGG) and converting. Here's what I found:
- For all my tests, downloading the best AAC directly (no conversion) was a win across the board. Best filesize, least processing time, equivalent or very close in quality
- OGG conversion did not make a meaningful (or any) change in quality but it made the filesize go way up
- OGG is a great format, but it has worse compatibility with iOS devices
- YouTube is inherently a BAD source for people who care about audio. You aren't getting …

Improve audio-only download

---

lib/pinchflat/profiles/media_profile.ex
lib/pinchflat/profiles/output_path_builder.ex
lib/pinchflat_web/components/layouts/root.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
lib/pinchflat_web/controllers/pages/page_controller.ex
lib/pinchflat_web/controllers/pages/page_html/onboarding_checklist.html.heex
test/pinchflat_web/controllers/page_controller_test.exs

- Adds a `{{ upload_yyyy_mm_dd }}` output path helper to return the `YYYY-MM-DD` upload date
- Disabled "pro" modal during onboarding. No need to overwhelm
- Improved the way onboarding tracks onboarding status so it doesn't re-run onboarding if you delete all your profiles/sources
- Updates the default media profile output template to include `{{ upload_yyyy_mm_dd }}`
N/A
N/A

Onboarding improvements

---

lib/pinchflat/yt_dlp/media_collection.ex
test/pinchflat/yt_dlp/media_collection_test.exs

N/A
N/A
- Fixes issue where `yt-dlp` would return a "No formats error" if the first video in a collection was set to premier in the future. Now, premiers are ignored (but will be downloaded at the next index once they've available). Brought to my attention by a Reddit comment
N/A

[Bugfix] Fixes issue with grabbing source/media details when first video is a premier

---

lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex

- Adds input validation to make sure the cutoff date is a string in the `YYYY-MM-DD` format with a max of 10 chars. Should help with some bug reports I've seen that stem from users putting in the date in the wrong format.
- Ensures year is in 1900-2099, month is in 01-12, and day is in 01-31. Does no validation for number of days in a month
N/A
N/A
N/A

Add input validation to help with cutoff date usage

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/metadata/metadata_parser.ex
lib/pinchflat/profiles/media_profile.ex
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/metadata/metadata_parser_test.exs
test/pinchflat/profiles_test.exs
test/pinchflat_web/controllers/media_profile_controller_test.exs

N/A
- Downloaded thumbnails are now appended with `-thumb` to be better supported by media centre apps
- NOTE: I'm pretty hesitant to base app decisions around the expectations other apps, but this one seemed like a good change across the board so it's now the default
- NOTE: I found a bug in yt-dlp when working on this and I've made a report for it: https://github.com/yt-dlp/yt-dlp/issues/9445
N/A
N/A

Append `-thumb` to thumbnails when downloading

---

config/config.exs
lib/pinchflat/boot/data_backfill_worker.ex
lib/pinchflat/filesystem/filesystem_data_worker.ex
lib/pinchflat/media/media.ex
lib/pinchflat/metadata/source_metadata.ex
lib/pinchflat/metadata/source_metadata_storage_worker.ex
lib/pinchflat/sources/source.ex
lib/pinchflat/sources/sources.ex
lib/pinchflat/tasks/tasks.ex
lib/pinchflat/yt_dlp/media_collection.ex
priv/repo/migrations/20240314174731_create_source_metadata.exs
test/pinchflat/metadata/source_metadata_storage_worker_test.exs
test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
test/pinchflat/sources_test.exs
test/pinchflat/yt_dlp/media_collection_test.exs
test/support/fixtures/sources_fixtures.ex

- Adds `source_metadata` model for tracking source metadata location
- Adds source metadata worker to fetch and store the aforementioned metadata. Kicks off when a source is created or updated
- Renamed `media_local_metadata` queue to `local_metadata`
N/A
Works toward #73 as well as #77

Squash all the commits from the other branch bc I broke things

---

lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/fast_indexing/fast_indexing_worker.ex
lib/pinchflat/fast_indexing/media_indexing_worker.ex
lib/pinchflat/media/media.ex
lib/pinchflat/metadata/source_metadata_storage_worker.ex
lib/pinchflat/slow_indexing/media_collection_indexing_worker.ex
lib/pinchflat/sources/sources.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/fast_indexing/fast_indexing_worker_test.exs
test/pinchflat/fast_indexing/media_indexing_worker_test.exs
test/pinchflat/metadata/source_metadata_storage_worker_test.exs
test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs

N/A
- Jobs are discarded if they raise an `Ecto.NoResultsError` or `Ecto.StaleEntryError`
- Possibly addresses a bug of unknown cause that happens when you delete a source immediately after starting indexing
N/A

Misc refactors 2024-03-15

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/downloading/media_downloader.ex
lib/pinchflat/metadata/metadata_file_helpers.ex
lib/pinchflat/metadata/nfo_builder.ex
lib/pinchflat/metadata/source_metadata_storage_worker.ex
lib/pinchflat/sources/source.ex
lib/pinchflat/sources/sources.ex
lib/pinchflat/yt_dlp/media_collection.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
priv/repo/migrations/20240318161405_add_nfo_path_to_sources.exs
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/metadata/metadata_file_helpers_test.exs
test/pinchflat/metadata/nfo_builder_test.exs
test/pinchflat/metadata/source_metadata_storage_worker_test.exs
test/pinchflat/sources_test.exs
test/pinchflat/yt_dlp/media_collection_test.exs
test/support/fixtures/sources_fixtures.ex

- Adds new fields to Source model for handling NFOs (`download_nfo`, `series_directory`, and `nfo_filepath`)
- Adds methods for determining the source's root filepath if it contains episodic media
- Adds methods for generating and storing an NFO for a source. Works toward #73 
- Updates source metadata worker to run `series_directory` determination as well as building + storing the NFO (if specified)
- Removes `premiered` tag in episode NFO and replaces it with the proper `aired` tag
N/A

Source NFO downloads

---

lib/pinchflat/slow_indexing/file_follower_server.ex
lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
lib/pinchflat/sources/source.ex
priv/repo/migrations/20240320181210_remove_unique_index_from_sources.exs
test/pinchflat/sources_test.exs

N/A
- Updates `FileFollowerServer`'s inactivity timeout from 1 minute to 10
- This has been working well and adding more headroom in case of slow requests is a good idea
- Removes the unique index that prevented multiple of the same sources being added to a media profile
- With the release of #98, there's now a valid use-case for using the same source multiple times with different regexes
- Updates various slow indexing methods to reload the source they're working with to pick up changes to settings like `download_media`. 
- This allows that setting to be changed mid-index and it'll start respecting it from that point on
N/A
N/A

Misc indexing improvements

---

.iex.exs
lib/pinchflat/boot/pre_job_startup_tasks.ex

N/A
N/A
- Adds pre-job startup task to set all jobs stuck in the `executing` state to `retryable` (resolves #111)
N/A

Adds a method for retrying stuck jobs

---

lib/pinchflat/downloading/output_path_builder.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex

- Adds `artist_name` custom output template placeholder
- Getting the artist's name from `yt-dlp` can be tricky if the uploader hasn't tagged their video correctly. This new placeholder attempts to use the artist, but falls back to creator and then uploader if needed. It's better than what it was!
- Updated the audio preset to use the new `artist_name` placeholder
N/A
N/A

Improve default recommendation for artist placeholder

---

lib/pinchflat/metadata/metadata_file_helpers.ex
lib/pinchflat/metadata/source_metadata.ex
lib/pinchflat/metadata/source_metadata_storage_worker.ex
priv/repo/migrations/20240325174728_add_image_attrs_to_source_metadata.exs
test/pinchflat/metadata/metadata_file_helpers_test.exs
test/pinchflat/metadata/source_metadata_storage_worker_test.exs

N/A
- Updates Source metadata worker to store source images in internal metadata directory (if present)
N/A
N/A

[Internal] Store source images in internal metadata

---

lib/pinchflat/boot/data_backfill_worker.ex
lib/pinchflat/boot/pre_job_startup_tasks.ex
test/pinchflat/boot/data_backfill_worker_test.exs

N/A
- Removes some old startup tasks used to get data in the correct state. I don't know why I didn't write a migration in the first place, but here we are
N/A
N/A

[Internal] Removed old startup tasks

---

lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html/show.html.heex

- Adds count of downloaded media to source show page (resolves #131)
N/A
N/A
N/A

[Enhancement] Show total count of downloaded media on Source page

---

lib/pinchflat_web/components/core_components.ex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex

N/A
- Enabling Fast Indexing now disables the Index Frequency field. Also sets its value to the 1 month value that fast indexing actually uses. Should help in situations like #132 
N/A
N/A

[Enhancement] Disable Index Frequency field when fast indexing is enabled

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/profiles/media_profile.ex
lib/pinchflat_web/components/core_components.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
priv/repo/migrations/20240328160057_add_sponsorblock_to_media_profiles.exs
test/pinchflat/downloading/download_option_builder_test.exs

- Adds ability to remove video sections based on SponsorBlock categories
- This is a setting on the Media Profile form
- Credit to `meeb/tubesync` for the section names!
N/A
N/A
N/A

[Feature] Add SponsorBlock-based section removal

---

README.md
config/config.exs
config/runtime.exs
config/test.exs
lib/pinchflat/release.ex

- Adds an ENV var to optionally change the SQLite journal mode in cases where the default of `wal` might not work (related to #137)
- Cleans up `runtime.exs` and `release.ex` a little
N/A
N/A

[Triage] Allow changing SQLite journal mode

---

lib/pinchflat/media/media_item.ex
lib/pinchflat/metadata/metadata_parser.ex
lib/pinchflat/podcasts/rss_feed_builder.ex
lib/pinchflat/yt_dlp/media.ex
priv/repo/migrations/20240328221845_add_duration_to_media_items.exs
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/metadata/metadata_parser_test.exs
test/pinchflat/yt_dlp/media_test.exs

- Adds attribute and logic for tracking media duration
- Adds duration attribute to RSS feed builder (related to #140)
N/A
N/A
N/A

[Enhancement] Start tracking a media item's duration

---

lib/pinchflat/sources/source.ex
priv/repo/migrations/20240401170440_re_re_add_source_uniqueness_index.exs
test/pinchflat/sources_test.exs

- Re-adds source uniqueness index, validating uniqueness by a combination of collection_id, media profile, and title regex (resolves #152)
- The unique index was removed in #99 since title regex meant it's valid to connect duplicate collections to one profile. But I figure we can make it unique, but based on `title_filter_regex` as well
N/A
N/A
N/A

[Housekeeping] Re-adds source uniqueness index

---

lib/pinchflat/media/media.ex
lib/pinchflat/media/media_item.ex
lib/pinchflat/media/media_query.ex
lib/pinchflat_web/controllers/media_items/media_item_controller.ex
lib/pinchflat_web/controllers/media_items/media_item_html.ex
lib/pinchflat_web/controllers/media_items/media_item_html/edit.html.heex
lib/pinchflat_web/controllers/media_items/media_item_html/media_item_form.html.heex
lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
lib/pinchflat_web/router.ex
priv/repo/migrations/20240402192417_add_prevent_download_to_media_items.exs
test/pinchflat/media_test.exs
test/pinchflat_web/controllers/media_item_controller_test.exs

- Adds `prevent_download` column to media item that stops a media item from being downloaded (or re-downloaded)
- Adds edit/update controller actions and UI for media items
- Update MI deletion via UI to delete the files but retain the database record
N/A
N/A

[Enhancement] Adds ability to stop media from re-downloading

---

lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/slow_indexing/media_collection_indexing_worker.ex
lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
lib/pinchflat_web/controllers/media_items/media_item_controller.ex
lib/pinchflat_web/controllers/media_items/media_item_html/actions_dropdown.html.heex
lib/pinchflat_web/controllers/media_items/media_item_html/media_item_form.html.heex
lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
lib/pinchflat_web/controllers/sources/source_html/show.html.heex
lib/pinchflat_web/router.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
test/pinchflat_web/controllers/media_item_controller_test.exs
test/pinchflat_web/controllers/source_controller_test.exs
test/support/conn_case.ex

- Updates source workers, controllers, and UI to allow forcing a re-index or downloading of pending items
- Updates media item workers, controllers, and UI to allow forcing download of an item
- Indexing and downloading workers now accept a `force` arg to run their task even when they otherwise wouldn't
- Refactored dropdowns into their own components
N/A
N/A

[Enhancement] Allow manual indexing/downloading

---

lib/pinchflat/boot/nfo_backfill_worker.ex
lib/pinchflat/boot/post_job_startup_tasks.ex
lib/pinchflat/metadata/nfo_builder.ex
lib/pinchflat/podcasts/rss_feed_builder.ex
lib/pinchflat/utils/xml_utils.ex
test/pinchflat/metadata/nfo_builder_test.exs
test/pinchflat/utils/xml_utils_test.exs

- Adds a startup worker that'll run one time ever to backfill NFO files
- Dynamic content in NFO files is now properly escaped. Possibly related to #167 
N/A
N/A

[Bugfix] Properly escape NFO files

---

lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/downloading/media_downloader.ex
lib/pinchflat/yt_dlp/command_runner.ex
lib/pinchflat/yt_dlp/media.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/yt_dlp/media_test.exs

N/A
- Sponsorblock failures now attempt to update the record with what data it _does_ have before scheduling a retry
- Media files will be written to disk without sponsorblock segments removed
- Before, some media files would download but the record wouldn't be updated until the job successfully retried
- Media files will be replaced once command successfully completes
- The download worker will no longer download a media item if it's `prevent_download` is `true`
N/A
There is currently an extended sponsorblock outage which let me both catch and test this 🤙

[Ehnacement] More gracefully handle Sponsorblock failures

---

README.md
config/config.exs
lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/downloading/media_redownload_worker.ex
lib/pinchflat/media/media.ex
lib/pinchflat/media/media_item.ex
lib/pinchflat/media/media_query.ex
lib/pinchflat/notifications/source_notifications.ex
lib/pinchflat/profiles/media_profile.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
lib/pinchflat_web/controllers/sources/source_controller.ex
priv/repo/migrations/20240409224152_add_redownloaded_fields.exs
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/downloading/media_redownload_worker_test.exs
test/pinchflat/media_test.exs

- Adds UI, columns, and workers to allow re-downloading new media after a set delay. This can help improve download quality or sponsorblock segments (resolves #127)
N/A
N/A
N/A

[Enhancement] Redownload new media after a delay

---

README.md
lib/pinchflat/boot/pre_job_startup_tasks.ex
lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/yt_dlp/command_runner.ex
test/pinchflat/boot/pre_job_startup_tasks_test.exs
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/yt_dlp/command_runner_test.exs

- Adds ability to use custom `yt-dlp` options via config files
- Resolves #174
- Resolves #175
- Supports both a base config that applies to all downloads and scoped configs that work on a per-profile/source/media basis 
- [Docs](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options)
N/A
N/A
N/A

[Enhancement] Allow custom yt-dlp options

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/profiles/media_profile.ex
lib/pinchflat/sources/source.ex
lib/pinchflat/sources/sources.ex
lib/pinchflat_web/controllers/sources/source_html.ex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
priv/repo/migrations/20240411154245_add_output_template_to_sources.exs
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/sources_test.exs

- Adds ability to specify an override for the Media Profile's output template on a per-source basis (Resolves #178)
- You need to enabled advanced mode when editing a source (button is in the upper right of the source form)
N/A
N/A
N/A

[Enhancement] Allow overriding output templates on a per-source basis

---

lib/pinchflat/downloading/download_option_builder.ex
test/pinchflat/downloading/download_option_builder_test.exs

N/A
N/A
- Resolves an issue where media metadata wasn't being imported by Plex since Plex doesn't support reading tags from `.mkv` files for some reason
- The fix is to remux to change out the mkv container for an mp4 container. This should be a no-op for all resolutions <= 1080p and only add a small processing time for larger files. Resolves #180
N/A

[Enhancement] Improve support for 4k videos with Plex

---

lib/pinchflat/downloading/download_option_builder.ex
test/pinchflat/downloading/download_option_builder_test.exs

N/A
- Changes embedded metadata date to `YYYY-MM-DD` to improve compatibility with Jellyfin (resolves #183)
N/A
N/A

[Enhancement] Improve embedded metadata date compatibility 

---

assets/js/app.js
dev.Dockerfile
lib/pinchflat/metadata/metadata_file_helpers.ex
lib/pinchflat_web/components/layouts/partials/upgrade_button_live.ex
lib/pinchflat_web/controllers/media_items/media_item_controller.ex
selfhosted.Dockerfile
test/pinchflat/media_test.exs
test/pinchflat/metadata/metadata_file_helpers_test.exs
test/pinchflat_web/controllers/media_item_controller_test.exs

N/A
- Manually installs mutagen since that was lost when I switched from python installation to binary installation
- Update media item metadata fetcher to pull the highest quality JPG
- Stopped "pro" upgrade form from submitting on enter (causing a page reload)
- Improved UX for forcing a download of a media item that already has a DL enqueued
N/A

[Bugfix]: Misc. bugfixes 2024-04-16

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/notifications/command_runner.ex
lib/pinchflat/utils/cli_utils.ex
lib/pinchflat/yt_dlp/command_runner.ex
lib/pinchflat/yt_dlp/media.ex
lib/pinchflat/yt_dlp/media_collection.ex
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/fast_indexing/fast_indexing_helpers_test.exs
test/pinchflat/sources_test.exs
test/pinchflat/yt_dlp/command_runner_test.exs

N/A
N/A
- Updates `yt-dlp` runner so all commands have the `--windows-filenames` flag  (resolves #191)
N/A

[Bugfix] Ensure source metadata fetching uses windows-compatible filepaths

---

lib/pinchflat/metadata/source_metadata_storage_worker.ex
lib/pinchflat/sources/sources.ex
lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html.ex
lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex
lib/pinchflat_web/router.ex
test/pinchflat/sources_test.exs
test/pinchflat_web/controllers/source_controller_test.exs

- Adds ability to force the refresh of a source's metadata from the actions menu
- Sources now only refresh their metadata (including images) when the `original_url` is changed instead of on _any_ change (resolves #185)
N/A
N/A

[Enhancement] Allow forcing a refresh of source metadata

---

lib/pinchflat/podcasts/rss_feed_builder.ex
lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
lib/pinchflat_web/router.ex
test/pinchflat/podcasts/rss_feed_builder_test.exs
test/pinchflat_web/controllers/podcast_controller_test.exs
test/support/fixtures/media_fixtures.ex

- Adds endpoints and XML for including episode images in podcast feeds (resolves #200)
- Some people (like me) prefer to use channel-level images in all cases. To support that, this feature uses the media thumbnails as the episode artwork. Don't want episode art? Don't download thumbnails 🤙 
N/A
N/A
N/A

[Enhancement] Optionally add episode art to podcast feeds

---

lib/pinchflat/notifications/source_notifications.ex
test/pinchflat/notifications/source_notifications_test.exs

N/A
N/A
- Stops Apprise notifications from being sent if the Source doesn't download media (resolves #215)
N/A

[Bugfix] Stop Apprise notifications from being sent if the Source doesn't download media

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/downloading/output_path_builder.ex
lib/pinchflat/media/media_item.ex
lib/pinchflat/media/media_query.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
priv/repo/migrations/20240502161955_add_upload_date_index_to_media_items.exs
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/downloading/output_path_builder_test.exs
test/pinchflat/media_test.exs
test/pinchflat/metadata/metadata_parser_test.exs

- Adds `upload_date_index` field to media items to act as a counter for the videos uploaded on that day for that source. (resolves #204, among others)
- This counter starts at 99 and counts down for channels OR starts at 0 and counts up for playlists. This ensures things stay organized even though channel videos are prepended and playlist videos are appended
- NOTE: this doesn't recompute the index numbers if, say, a private video is made public in the middle of the list. This reaction to this extreme edge case is considered expected
- Adds `{{ season_episode_index_from_date }}` template placeholder to support new index capabilities
- Updates the template parser to recursively parse additional options passed to it (one layer deep)
- Updates `build_output_path_for` to take a media_item
N/A …

[Enhancement] Add Media Center support for videos uploaded on the same day

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/metadata/metadata_file_helpers.ex
lib/pinchflat/metadata/metadata_parser.ex
lib/pinchflat/yt_dlp/media.ex
lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/metadata/metadata_file_helpers_test.exs
test/pinchflat/metadata/metadata_parser_test.exs
test/pinchflat/yt_dlp/media_test.exs

N/A
- Audio-only sources now have a proper precedence set if an m4a cannot be found
- `livestream` is set to false if not present in the attributes payload
- Thumbnail downloads now work if they aren't returned with a `preference` field
- Thumbnails will now allow non-jpg images to download, but jpg is has a significantly higher priority
- `Open Original` in the Media Item show page is no longer present if the `original_url` field doesn't contain a valid URI
N/A
N/A

[Housekeeping] Improved robustness of metadata parsing

---

config/prod.exs
dev.Dockerfile
lib/pinchflat_web/components/custom_components/text_components.ex
selfhosted.Dockerfile

N/A
Resolves #230 
- Pre-build FFMPEG using yt-dlp's custom FFMPEG
- Remove git from release dockerfile
- Use pipx instead of pip to install Apprise
- Consolidate as many docker commands as possible
With these changes the uncompressed size went from 1.12GB to ~650MB and the compressed size from 450 MB to 250 MB 🎉 
N/A
N/A

[Housekeeping] Reduce Docker image size

---

config/prod.exs
config/runtime.exs
lib/pinchflat/release.ex

N/A
- Allows specifying where to store Elixir's internal timezone database via `TZ_DATA_DIR`
- Can be helpful when working with read-only filesystems (resolves #237)
N/A
N/A

[Enhancement] Made timezone data location user-configurable

---

config/config.exs
lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/downloading/downloading_helpers.ex
lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/downloading/media_downloader.ex
lib/pinchflat/downloading/media_quality_upgrade_worker.ex
lib/pinchflat/fast_indexing/fast_indexing_helpers.ex
lib/pinchflat/lifecycle/notifications/source_notifications.ex
lib/pinchflat/media/media.ex
lib/pinchflat/media/media_item.ex
lib/pinchflat/media/media_query.ex
lib/pinchflat/podcasts/podcast_helpers.ex
lib/pinchflat/sources/sources.ex
lib/pinchflat_web/components/custom_components/table_components.ex
lib/pinchflat_web/controllers/pages/page_controller.ex
lib/pinchflat_web/controllers/pages/page_html/history_table_live.ex
lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
lib/pinchflat_web/controllers/sources/source_html/media_item_table_live.ex
lib/pinchflat_web/router.ex
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/downloading/downloading_helpers_test.exs
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/downloading/media_quality_upgrade_worker_test.exs
test/pinchflat_web/controllers/source_controller_test.exs

- Adds the ability to re-run a download for existing media items (works toward #202)
- This is useful for picking up changes to a source/media profile. For example, if you index + download a source without downloading thumbnails but then change your mind, this can be used to download thumbnails for all your existing media
- NOTE: this will do a full re-download of _everything_ if the expected filepath changes (ie: you update your output path template)
- Adds ability to specify custom overrides for media downloading (currently only supports `overwrite_behaviour`)
- Renames `MediaRedownloadWorker` to `MediaQualityUpgradeWorker` to better describe what it actually does and disambiguate it from the new redownload work in this PR
N/A
N/A

[Enhancement] Allow redownloading of files for existing media items

---

lib/pinchflat/podcasts/podcast_helpers.ex
lib/pinchflat/podcasts/rss_feed_builder.ex
lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
priv/repo/migrations/20240515163649_add_date_indexes_to_media_items.exs
test/pinchflat/podcasts/podcast_helpers_test.exs

- Adds index for a media item's download and redownload dates
- Increases limit on RSS feed from 300 to 2,000 (resolves #240)
- Orders RSS feed by upload date with the newest items being on top (resolves #240)
N/A

[Bugfix] Order RSS feed by upload date

---

.sobelow-conf
config/runtime.exs
lib/pinchflat_web/components/layouts.ex
lib/pinchflat_web/components/layouts/app.html.heex
lib/pinchflat_web/components/layouts/partials/sidebar.html.heex
lib/pinchflat_web/controllers/settings/setting_controller.ex
lib/pinchflat_web/controllers/settings/setting_html.ex
lib/pinchflat_web/controllers/settings/setting_html/app_info.html.heex
lib/pinchflat_web/router.ex
test/pinchflat_web/controllers/setting_controller_test.exs

- Adds a page to copy basic details of your installation or download your logs in-app (related to #236)
- Adds new `sidebar_submenu` component
- Sets default log level to debug
N/A
N/A

[Enhancement] Adds in-app diagnostics page

---

lib/pinchflat/lifecycle/notifications/command_runner.ex
lib/pinchflat/lifecycle/user_scripts/command_runner.ex
lib/pinchflat/utils/cli_utils.ex
lib/pinchflat/yt_dlp/command_runner.ex
lib/pinchflat/yt_dlp/media_collection.ex
test/pinchflat/yt_dlp/command_runner_test.exs
test/pinchflat/yt_dlp/media_collection_test.exs

N/A
- Updates `CliUtils` to always log the result of a call to an executable (related to #236)
N/A
N/A

[Housekeeping] Improved logging for all executable calls

---

lib/pinchflat/boot/pre_job_startup_tasks.ex
lib/pinchflat/utils/cli_utils.ex
test/pinchflat/boot/pre_job_startup_tasks_test.exs
test/pinchflat/utils/cli_utils_test.exs

N/A
N/A
yt-dlp causes an error when it tries to write to a read-only directory. It'll attempt this illegal write if it scans a video that is < ~48 hours old (ie: its only available format is a m3u8 [#616]) AND windows filename compatibility is enabled. The underlying reason isn't fully known. 
This fix gets around this by executing the command from the tmp directory, ensuring it has write access. Related to #236 
N/A

[Bugfix] Fix yt-dlp illegal write issue that causes failure to fetch source details

---

lib/pinchflat/downloading/codec_parser.ex
lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat/settings/setting.ex
lib/pinchflat_web/controllers/media_items/media_item_html.ex
lib/pinchflat_web/controllers/media_items/media_item_html/media_item_form.html.heex
lib/pinchflat_web/controllers/settings/setting_controller.ex
lib/pinchflat_web/controllers/settings/setting_html.ex
lib/pinchflat_web/controllers/settings/setting_html/codec_settings_help.html.heex
lib/pinchflat_web/controllers/settings/setting_html/setting_form.html.heex
priv/repo/migrations/20240521193719_add_codec_preferences_to_settings.exs
test/pinchflat/downloading/codec_parser_test.exs
test/pinchflat/downloading/download_option_builder_test.exs
test/pinchflat/settings_test.exs

- Adds ability to specify desired codec preferences for video and audio (works toward #252)
- NOTE: this is intentionally a "soft" preference - the best available codec will be chosen if your preferred codecs aren't available
- Adds "advanced mode" UI to the settings page
N/A
N/A
N/A

[Enhancement] Allow setting preference for video/audio codec

---

lib/pinchflat_web/controllers/sources/source_html/media_item_table_live.ex
lib/pinchflat_web/controllers/sources/source_html/show.html.heex
test/pinchflat_web/controllers/sources/media_item_table_live_test.exs

- Adds "other" tab to source view to capture media that's not pending or downloaded. This can be media that's explicitly ignored or not picked up due to settings on the source/media profile (resolves #257)
- Updates `MediaItemTableLive` so that all tables are reloaded when one is reloaded
N/A
N/A
N/A

[Enhancement] Added "other" tab to see media that's not set for download

---

lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/media/file_deletion.ex
lib/pinchflat/utils/filesystem_utils.ex
lib/pinchflat/utils/map_utils.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/media/file_deletion_test.exs
test/pinchflat/utils/filesystem_utils_test.exs
test/pinchflat/utils/map_utils_test.exs
test/support/files/subtitle.srt
test/support/fixtures/media_fixtures.ex

N/A
N/A
- Fixes a bug where, if a video's name changes between original download and quality upgrade, the video is duplicated with both the old and new name
- Resolves #389
N/A

[Bugfix] prevent duplicate videos from being downloaded if the video's name changes

---

lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/media/file_syncing.ex
lib/pinchflat/media/file_syncing_worker.ex
lib/pinchflat_web/controllers/sources/source_controller.ex
lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
lib/pinchflat_web/router.ex
test/pinchflat/media/file_syncing_test.exs
test/pinchflat/media/file_syncing_worker_test.exs
test/pinchflat_web/controllers/source_controller_test.exs

- Adds the ability to run a file sync on a source. This checks each media item's various filepaths to see if it still exists on-disk at the specified location. If not, the media item sets that filepath to `nil`
- Useful for recovering if you've run a mass-deletion of your files by accident
- Doesn't intelligently interpret file moves or additions, only deletions. Any time a file is expected at a certain location but isn't actually found there is considered a deletion (ie: a move would also count as a deletion)
- Resolves #393
N/A
N/A
N/A

[Enhancement] Added ability to detect when files have been deleted

---

lib/pinchflat_web/components/layouts.ex

N/A
The arrow indicating that Config has a submenu / is an accordion is currently facing up when unopened, and down when opened:
It's pretty much UI-standard to mark a collapsed menu with an arrow facing down, indicating that it can be _dropped-down_. (also common: the arrow facing ~the menu name~ **away from the menu name**, rotating upwards once opened)
I would link some examples and studies (here's [one](https://www.nngroup.com/articles/accordion-icons)), but I'm pretty sure you know this since...
https://github.com/kieraneglin/pinchflat/blob/944d26b57d7f183c63a92ec438531f2e9b7f9deb/lib/pinchflat_web/components/custom_components/button_components.ex#L70-L74
All I have done is change the class name for the chevron symbol to a `down` variant, as used in the code above.
N/A
I also made a …

Flip Config submenu arrow

---

README.md

N/A
Tiny change to the readme to make the reverse proxy config easier to figure out. I had to dig into past PRs and found it in the discussion of #275 to figure it out.
N/A
N/A

[Docs] document that BASE_ROUTE_PATH requires the prefix to be stripped

---

lib/pinchflat/sources/sources.ex
lib/pinchflat/yt_dlp/media_collection.ex
test/pinchflat/sources_test.exs
test/pinchflat/yt_dlp/media_collection_test.exs

N/A
- Adds an error message when a source is added with a URL that `yt-dlp` accepts but can't return any details for (eg: `https://www.youtube.com/feed/subscriptions`)
- Resolves #404
N/A
N/A

[Enhancement] Improve error message when adding a source who's details can't be queried by URL

---

README.md
docker/selfhosted.Dockerfile

N/A
- Previously, you could assume root with `su`. Now you can't do that and have to instead do something like `docker exec -it --user root pinchflat bash`
N/A
N/A

[Housekeeping] Reinstated container root password rules

---

lib/pinchflat/media/media.ex
test/pinchflat/media_test.exs

N/A
N/A
- Took the easy way out and specifically omitted `playlist_index` as a field that can be updated
- Resolves #409
N/A

[Bugfix] Ensure that `playlist_index` remains persisted in all cases

---

lib/pinchflat/yt_dlp/media.ex
test/pinchflat/fast_indexing/fast_indexing_helpers_test.exs
test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
test/pinchflat/yt_dlp/media_test.exs
test/support/fixtures/media_fixtures.ex
test/support/fixtures/sources_fixtures.ex

N/A
- Reverts #59 so we now use `original_url` in the indexing output template again. I can't remember the reason for the original switch, but it must've increased reliability in detecting shorts. Anyway, since a new bunch of shorts-related issues have cropped up I've switched back since `original_url` now more reliably returns `/shorts/` in the URL when indexing a channel
- Resolves #415 
N/A
N/A

[Enhancement] Improve short detection logic (again)

---

docker/selfhosted.Dockerfile
lib/pinchflat/boot/pre_job_startup_tasks.ex
lib/pinchflat/lifecycle/user_scripts/command_runner.ex
lib/pinchflat/release.ex
test/pinchflat/boot/pre_job_startup_tasks_test.exs

**TODO:** Remove draft comment [here](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-yt%E2%80%90dlp-plugins)
**TODO:** Document this new lifecycle event [here](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-lifecycle-scripts)
- Adds a new `app_init` lifecycle event that can be used in custom lifecycle scripts
- Can be used to install plugins, among other things
- Adds new in-container directory for holding plugins at `/etc/yt-dlp/plugins`
- This directory was chosen per the yt-dlp plugin installation [instructions](https://github.com/yt-dlp/yt-dlp#installing-plugins)
- Adds `zip` to the selfhosted Dockerfile's packages to aid in installing plugins programatically  
- Resolves #448
N/A
N/A
N/A

[Enhancement] Add support for yt-dlp plugins + add lifecycle script event for app boot

---

lib/pinchflat_web/controllers/media_profiles/media_profile_controller.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/actions_dropdown.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/media_profile_form.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/new.html.heex
lib/pinchflat_web/controllers/sources/source_controller.ex
test/pinchflat_web/controllers/media_profile_controller_test.exs

Replicated the "Use as Template" feature from Sources to Media Profiles. Existing profile can now be used as a template to create new profiles as requested in #459. Option can be found under the Actions dropdown in the Media Profile view.
N/A
N/A
There was some weird behavior: It seems like having parameters in the new Profile form fires a PUT request instead of a POST request like it should. To fix that I basically replicated what was done on the Source form and specified explicit methods. All tests are now passing.
Closes #459

[Enhancement] Add option to use existing Media Profile as template for new profile

---

lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/downloading/media_downloader.ex
lib/pinchflat/yt_dlp/media.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/yt_dlp/media_test.exs

N/A
N/A
- Previously, we relied purely on methods like `Media.pending_download?` to determine both if something _should_ be downloaded and if something is _ready_ to be downloaded. It works great for the former, but didn't work as well for the latter (esp. around some edge cases with fast indexing). Now, there's an explicit pre-check in `MediaDownloader` to ensure that the media is actually in a state that it can be downloaded. If it's not, we'll check again _during the next indexing pass (both slow and fast indexing)_ . This could conceivably change in the future but this is a proof-of-concept
- Resolves #395 
- Resolves #480
N/A

[Bugfix] Ensure livestreams aren't downloaded until they're finished processing

---

lib/pinchflat_web/controllers/sources/source_html.ex
lib/pinchflat_web/controllers/sources/source_html/source_form.html.heex

- Adds a selection box that, on change, automatically sets the cutoff date based on your selection
- Related to #451
- Unsetting the selection box reverts the cutoff date to what it was before
N/A
N/A
N/A

[Enhancement] Add presets to cutoff date input

---

lib/pinchflat_web/controllers/pages/page_html/history_table_live.ex
lib/pinchflat_web/controllers/pages/page_html/job_table_live.ex
lib/pinchflat_web/controllers/searches/search_html/show.html.heex
lib/pinchflat_web/controllers/sources/source_html/index_table_live.ex
lib/pinchflat_web/controllers/sources/source_html/media_item_table_live.ex

N/A
- Truncating titles in tables via css to allow browser to show more of the title if space is available.
- closes #506
- related to #458
N/A
N/A

truncate table columns via css

---

lib/pinchflat_web/controllers/pages/page_html/history_table_live.ex
lib/pinchflat_web/controllers/pages/page_html/home.html.heex

- closes #504
N/A
Media history separated tabs for downloaded and pending media items.
N/A
N/A

Separate tabs for pending and downloaded in media history

---

lib/pinchflat/utils/string_utils.ex
lib/pinchflat_web/components/custom_components/button_components.ex
lib/pinchflat_web/components/custom_components/table_components.ex
lib/pinchflat_web/controllers/media_items/media_item_html/edit.html.heex
lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/edit.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/index.html.heex
lib/pinchflat_web/controllers/media_profiles/media_profile_html/show.html.heex
lib/pinchflat_web/controllers/searches/search_html/show.html.heex
lib/pinchflat_web/controllers/sources/source_html/edit.html.heex
lib/pinchflat_web/controllers/sources/source_html/show.html.heex
lib/pinchflat_web/controllers/sources/source_live/index_table_live.html.heex
test/pinchflat/utils/string_utils_test.exs
test/pinchflat_web/controllers/pages/job_table_live_test.exs

Added truncated for source names and media profile names
- Replace all usages of StringUtils.truncate with css truncate
- Prevent text wrapping in buttons
Resolves: #458 
N/A
N/A

use css truncate everywhere and remove StringUtils.truncate function

---

lib/pinchflat/yt_dlp/command_runner.ex
lib/pinchflat/yt_dlp/media.ex
lib/pinchflat/yt_dlp/media_collection.ex
lib/pinchflat/yt_dlp/yt_dlp_command_runner.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/fast_indexing/fast_indexing_helpers_test.exs
test/pinchflat/fast_indexing/fast_indexing_worker_test.exs
test/pinchflat/media_test.exs
test/pinchflat/metadata/metadata_file_helpers_test.exs
test/pinchflat/metadata/source_metadata_storage_worker_test.exs
test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
test/pinchflat/sources_test.exs
test/pinchflat/yt_dlp/command_runner_test.exs
test/pinchflat/yt_dlp/media_collection_test.exs
test/pinchflat/yt_dlp/media_test.exs
test/pinchflat_web/controllers/pages/job_table_live_test.exs
test/pinchflat_web/controllers/source_controller_test.exs

- All calls to the yt-dlp runner now pass an `action` argument where the action is typically the current method name
- This resolves a long-standing issue with the way yt-dlp is mocked in tests. Since there's only one "entrypoint" into yt-dlp, it made mocking with Mox extremely error prone and fragile since mocks would have to either abuse the fact that _some_ yt-dlp calls had different arity or pattern match against things like the output template. The new approach allows me to match based on the _action_ being taken (a proxy for a method name in a more typical setup) and now I can be sure that I'm mocking the correct thing and I don't have to resort to sketchy bodges. Again, this isn't typically an issue but it was in this case since the `run` method is essentially an opaque entrypoint …

[Housekeeping] Pass the current action when calling the yt-dlp runner

---

lib/pinchflat/downloading/media_downloader.ex
lib/pinchflat/yt_dlp/media.ex
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/yt_dlp/media_test.exs

N/A
N/A
- Updates the media download pre-check to use the same cookie rules as would be used to actually download the media
- Resolves #509
N/A

[Bugfix] Respect cookies preference when performing download pre-check

---

lib/pinchflat/podcasts/opml_feed_builder.ex
lib/pinchflat/podcasts/podcast_helpers.ex
lib/pinchflat_web/controllers/podcasts/podcast_controller.ex
lib/pinchflat_web/controllers/sources/source_html.ex
lib/pinchflat_web/controllers/sources/source_html/index.html.heex
lib/pinchflat_web/router.ex
test/pinchflat/podcasts/opml_feed_builder_test.exs
test/pinchflat/podcasts/podcast_helpers_test.exs
test/pinchflat_web/controllers/podcast_controller_test.exs

Added an endpoint that provides an OPML-XML of all sources. Resolves #449 
N/A
N/A
N/A

Added OPML Endpoint for podcast rss feeds

---

lib/pinchflat/slow_indexing/media_collection_indexing_worker.ex
lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
lib/pinchflat/utils/filesystem_utils.ex
lib/pinchflat/yt_dlp/command_runner.ex
lib/pinchflat/yt_dlp/media_collection.ex
lib/pinchflat_web/controllers/sources/source_html/actions_dropdown.html.heex
test/pinchflat/slow_indexing/media_collection_indexing_worker_test.exs
test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
test/pinchflat/yt_dlp/command_runner_test.exs
test/support/scripts/yt-dlp-mocks/101_exit_code.sh

N/A
This is a very meaningful change to the way indexing works but you can skip to the bottom for a tl;dr
**Background**
Before, any indexing run would read the entire contents of a channel and capture everything, every time. This was initially seen as an advantage for two reasons:
1. Changes made by the uploader would be picked up and reflected in the media items (eg: a title change)
2. Previously private videos would be captured if they were made public once again
In practice, the former rarely happens after the first few days of a video's upload and the latter happens so infrequently as to not be worth hinging such a big design decision on. I wouldn't have made this PR if it were just about idealized design choices - there are some real downsides to this approach:
- Indexing is a very …

[Enhancement] Overhaul indexing to be more efficient

---

lib/pinchflat/downloading/download_option_builder.ex
lib/pinchflat_web/controllers/media_profiles/media_profile_html.ex

- Adds `{{ media_profile_id }}`, `{{ source_id }}`, and `{{ media_item_id }}` as options to the output template builder. Can be used to split media into "seasons" based on ID (usually the source ID). See #534 for rationale
- Resolves #534
N/A
N/A
N/A

[Enhancement] Add media profile, source, and media item IDs as options for output templates

---

docker/selfhosted.Dockerfile

N/A
- Updates the Docker healthcheck to run every 30s instead of every 2 minutes
- Resolves #552 
N/A
N/A

[Housekeeping] Update Docker healthcheck to run every 30s

---

lib/pinchflat/settings/setting.ex
test/pinchflat/settings_test.exs

N/A
N/A
- Fixes bug where you couldn't reset the sleep interval to 0 for rate limiting
- Resolves #569
N/A

[Bugfix] Allow resetting rate limit sleep interval

---

lib/pinchflat/downloading/media_download_worker.ex
test/pinchflat/downloading/media_download_worker_test.exs

N/A
- Before, the download job didn't check for whether a media item was pending download before running the download itself. We checked its pending status _before_ enqueuing the job but the side effect is that the job runner would still download the media item even if the source's settings changed sometime between enqueing the job and the job actually running. Now, the download job pre-checks that the media item is actually pending before downloading (unless forced)
- Resolves #568
N/A
N/A

[Enhancement] Re-check if media is pending immediately before download

---

lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs

N/A
N/A
- Updates download archive logic to avoid creating an archive if the source has never been indexed
- Resolves #573 
N/A

[Bugfix] Ensure a full indexing pass always runs if the source has never been indexed before

---

config/runtime.exs
lib/pinchflat/downloading/downloading_helpers.ex
lib/pinchflat/downloading/media_download_worker.ex
lib/pinchflat/fast_indexing/fast_indexing_helpers.ex
lib/pinchflat/fast_indexing/fast_indexing_worker.ex
lib/pinchflat/slow_indexing/slow_indexing_helpers.ex
lib/pinchflat/sources/sources.ex
test/pinchflat/downloading/downloading_helpers_test.exs
test/pinchflat/downloading/media_download_worker_test.exs
test/pinchflat/fast_indexing/fast_indexing_helpers_test.exs
test/pinchflat/slow_indexing/slow_indexing_helpers_test.exs
test/pinchflat/sources_test.exs

N/A
- Sources now kick off fast indexing immediately when created (if that option is checked)
- This allows the first handful of media items to get enqueued for download on source creation even if there are long-running indexing tasks going on in the background
- Media downloads queued up by fast indexing have a higher priority than downloads from slow indexing
- Related to https://github.com/kieraneglin/pinchflat/issues/573#issuecomment-2605764052
- Updated the count of concurrent fast indexing queues to respect `yt_dlp_worker_count` since these workers do indeed call out to yt-dlp
N/A

[Enhancement] Run fast indexing on source creation and at higher priority

---

config/config.exs
config/runtime.exs
lib/pinchflat/application.ex
lib/pinchflat/boot/post_boot_startup_tasks.ex
lib/pinchflat/boot/post_job_startup_tasks.ex
lib/pinchflat/boot/pre_job_startup_tasks.ex
lib/pinchflat/profiles/media_profile_deletion_worker.ex
lib/pinchflat/yt_dlp/command_runner.ex
lib/pinchflat/yt_dlp/update_worker.ex
lib/pinchflat/yt_dlp/yt_dlp_command_runner.ex
lib/pinchflat_web/endpoint.ex
test/pinchflat/boot/post_boot_startup_tasks_test.exs
test/pinchflat/yt_dlp/command_runner_test.exs
test/pinchflat/yt_dlp/update_worker_test.exs

- Automatically updates yt-dlp on app boot and once daily thereafter
- Instead of a daily check at a set time, it schedules the update daily at the time of app boot. This ensures all instances don't hit the update at the same time and it buys me a little time if a yt-dlp update breaks things
- I initially didn't add this since I wanted to be able to update and test any changes myself, but it's been almost a year and I've encountered _far_ more issues from delaying yt-dlp updates compared to an update causing compatibility issues
N/A
N/A
N/A

[Enhancement] Auto-update yt-dlp

---

lib/pinchflat/fast_indexing/youtube_api.ex
lib/pinchflat_web/controllers/settings/setting_html/setting_form.html.heex
test/pinchflat/fast_indexing/youtube_api_test.exs

Add support for multiple comma separated YouTube API keys.
N/A
N/A
I am pretty unfamiliar with Elixir, so forgive me if my code is atrocious.
This helps users who use the api with many sources and hit the daily limit.
Nothing changes for other users and there is effectively no downside.
Nothing changes in the database, we just parse the comma separated values when we need a key.
This uses a round-robin approach for cycling through the keys. I chose it because it evenly uses the keys and is pretty simple.
The other options I thought of were:
- random number: no agent, but not as uniform for api usage
- use one key until (nearly) full: only use other keys when you actually need them, but need to keep track of each key's state.
All tests pass for me

[Enhancement] Support Multiple YouTube API Keys

---

lib/pinchflat/downloading/media_download_worker.ex
test/pinchflat/downloading/media_download_worker_test.exs

N/A
- Download failures due to content being members-only now results in the job being discarded rather than retried. Like other non-recoverable failures, the app will try again during the next indexing pass. If you need to manually retry the download you can use the "Download Pending" button when looking at the source
- Resolves #588
N/A
N/A

[Enhancement] Download failures due to videos being members-only are not immediately retried

---

lib/pinchflat/yt_dlp/media.ex
test/pinchflat/yt_dlp/media_test.exs

N/A
The title is a joke - don't yell at me
- Updates shorts detection logic to go from a cutoff of 60s to a cutoff of 180s to reflect the change in max shorts duration
- Resolves #612 
N/A
N/A

[Bugfix] Improve YouTube shorts detection for new YouTube pants

---

docker/selfhosted.Dockerfile

N/A
N/A
- Updates permissions in the Dockerfile so that yt-dlp can self-update
- Resolves #625 
N/A

[Bugfix] Improve yt-dlp permissions to allow auto update

---

lib/pinchflat/downloading/media_downloader.ex
lib/pinchflat/sources/sources.ex
test/pinchflat/downloading/media_downloader_test.exs
test/pinchflat/sources_test.exs

- If a source's `cookie_behaviour` is set to `when_needed` and a video is encountered that is age-restricted/members-only, the download is retried but this time cookies are used (if present)
N/A
N/A
N/A

[Enhancement] Retry a download using cookies if doing so might help

---

README.md

Readme guide: Docker always has a tendency to get in my way on Debian. Also, I really like the userns setup for podman for giving permissions between host and container.
Add README info for Podman
No worries if you don't want to take the PR. Just thought it could help some folks.

[Docs] Add podman to README

---

lib/pinchflat_web/components/layouts/partials/sidebar.html.heex

N/A
N/A
- Uses p-sigil for header homepage link so `BASE_ROUTE_PATH` is respected
- Resolves #688
N/A

[Bugfix] Fix header link when using `BASE_ROUTE_PATH`
